### ISSUE TITLE
Per VIRTUAL_HOST / VIRTUAL_PORT config

### ISSUE THREAD

**Issue by egandro** [pini-gh/nginx-proxy#70]
Hello. I am unsing "sonatype/nexus3"

The container exposes 8081 as default. You can add a 2nd port (later after the installation) and give it e.g. 8082. 
Note 8082 might be not available when I start the container the first time.

I want the following mapping.

nexus.mydomain.tld -> 8081
registry.mydomain.tld -> 8082

Is this possible with your patch?

Thx.

**Comment by pini-gh** [comment]
> I want the following mapping.
> 
> nexus.mydomain.tld -> 8081 registry.mydomain.tld -> 8082
> 
> Is this possible with your patch?

Yes it is :
```
VIRTUAL_HOST=nexus.mydomain.tld:8081,registry.mydomain.tld:8082
```

**Comment by egandro** [comment]
thx a lot!
