### ISSUE TITLE
Adding a multiport container suppresses all other containers on that VIRTUAL_HOST

### ISSUE THREAD

**Issue by allen-pattern** [pini-gh/nginx-proxy#78]
Using `pinidh/nginx-proxy:latest@sha256:9d5083d65dbb66aad66476caa00e4c0054d1bafabfd4e85a132cf86f6b62904e`. I have:
- A container with `VIRTUAL_HOST=mywebsite` and `VIRTUAL_PATH=/`
- A container with `VIRTUAL_HOST=mywebsite` and `VIRTUAL_PATH=/auth`
- A container with `VIRTUAL_HOST=mywebsite`, `VIRTUAL_PATH=/api/path`, and `VIRTUAL_DEST=/path`

All of these three work fine, and `nginx -T` returns what you'd expect for all of them, and the ports are inferred. As soon as I add in:

- A container with `VIRTUAL_HOST=mywebsite` and `VIRTUAL_PORT=8199:~ ^/(pathone|pathtwo|paththree)/,8197:/pathfour:/`

The other three no longer generate entries; only the fourth one does. As soon as I shut down the fourth one, its entries disappear and the ones for the other three reappear. When I start it back up, its entries appear and the other entries disappear. Removing the second VIRTUAL_PORT entry does not help, so it seems that it is not necessarily a problem with multiport routing but with the new config format. Incidentally, another VIRTUAL_HOST I have configured on the same box is unaffected. Any way to avoid this? Thanks in advance.

**Comment by pini-gh** [comment]
This is expected. See this note at the end of the multiport syntax section of the README.md:
> Important note: All VIRTUAL_PATH variables will be ignored for any virtual host appearing in a at least one container where VIRTUAL_PORT uses the multiport syntax, .

You have to use multiport syntax for the first three containers as well, instead of `VIRTUAL_PATH`.

**Comment by pini-gh** [comment]
No more activity after 1 month. Closing.
